"""Create File metadata model

Revision ID: 124a0f779f70
Revises: 0d484ae1ab22
Create Date: 2024-07-04 21:24:45.726493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '124a0f779f70'
down_revision = '0d484ae1ab22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('line_content', sa.Text(), nullable=False),
    sa.Column('line_size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_metadata')
    # ### end Alembic commands ###
